from dungeon.models.EnemySkill import EnemySkill

generic_symbols = {
    'bind': "❌",
    'blind': "😎",
    'super_blind': "😎😎",
    'to': "➡",
    'attack': '🤜',
    'multi_attack': '🤜🤜',
    'self': '👹',
    'health': '❤',
}

skyfall_symbols = {
    'super_blind': "😎🌧️",
    'no': "🛑🌧",
    'fire': "🔥🌧",
    'water': "🌊🌧",
    'wood': "🌿🌧",
    'dark': "🌙🌧",
    'light': "💡🌧",
    'heal': "🩹🌧",
    'poison': "☠🌧",
    'mortal poison': "☠☠🌧",
    'jammer': "🗑️🌧",
    'locked fire': "🔒🔥🌧",
    'locked water': "🔒🌊🌧",
    'locked wood': "🔒🌿🌧",
    'locked dark': "🔒🌙🌧",
    'locked light': "🔒💡🌧",
    'locked heal': "🔒🩹🌧",
    'locked poison': "🔒☠🌧",
    'locked mortal poison': "🔒☠☠🌧",
    'locked jammer': "🔒🗑️🌧",
    'locked bomb': '🔒💣🌧',
    'locked random': '🔒Random🌧'
}

skills_dict = {
    'awoken': "👁️",
    'active': "🪄",
    'recover': "🏥",
    'roulette': "🎰",
}

attribute_type_dict = {
    'awoken': "👁️",
    'active': "🪄",
    'recover': "🏥",
    'roulette': "🎰",
    'dragon': "🐉",
    'balanced': "⚖",
    'physical': "🛡️",
    'healer': "❤",
    'attacker': "⚔",
    'god': "😇",
    'devil': "😈",
    'machine': "⚙",
    'fire': "🔥",
    'water': "🌊",
    'wood': "🌿",
    'dark': "🌙",
    'light': "💡",
    'heal': "🩹",
    'poison': "☠",
    'mortal poison': "☠☠",
    'jammer': "🗑️",
    'locked fire': "🔒🔥",
    'locked water': "🔒🌊",
    'locked wood': "🔒🌿",
    'locked dark': "🔒🌙",
    'locked light': "🔒💡",
    'locked heal': "🔒🩹",
    'locked poison': "🔒☠",
    'locked mortal poison': "🔒☠☠",
    'locked jammer': "🔒🗑️",
    'locked bomb': '🔒💣',
    'locked random': '🔒Random',
    'bomb': '💣',
    'unknown': "❓",
    'blocked fire': "🚫🔥",
    'blocked water': "🚫🌊",
    'blocked wood': "🚫🌿",
    'blocked dark': "🚫🌙",
    'blocked light': "🚫💡",
    'blocked heal': "🚫🩹",
    'blocked poison': "🚫☠",
    'blocked mortal poison': "🚫☠☠",
    'blocked jammer': "🚫🗑️",
    'blocked bomb': '🚫💣',
    'blocked random': '🚫Random',
    'attack': "🗡️",
    'defense': "🛡️",
    'defense25': "🛡️25%",
    'defense50': "🛡️50%",
    'defense75': "🛡️75%",
    'defense80': "🛡️80%",
    'defense90': "🛡️90%",
    'defense95': "🛡️95%",
    'defense99': "🛡️99%",
    'combo': "🌪️",
    'absorb': "🌪️",
    'damage_absorb': "🗡️🌪️",
    'void': "🧱",
    'status_shield': "🛡️Status",
    'fire_absorb': "🔥🌪️",
    'water_absorb': "🌊🌪️",
    'wood_absorb': "🌿🌪️",
    'dark_absorb': "🌙🌪️",
    'light_absorb': "💡🌪️",
    'resolve': "👌",
    'rcv_buff': "🩹⬆️",
    'atk_debuff': "🗡️⬇️",
    'rcv_debuff': "🩹⬇️",
    'time_buff': "☝⬆",
    'time_debuff': "☝⬇",
    'dispel': "(Dispel)",
    'swap': "♔🔀",
    'skill_delay': '🔋',
    'locked': '🔒',
    'tape': '🧻',
    'starting_position': '☝🎯',
    'cloud': '☁',
    'gravity': '💔',
    'invincible': '🛡️🛡️🛡️',
    'invincible_off': '🛡️🛡️🛡️❌',
    'force_target': '🎯',
    'leader_alter': '♔➡',
    'board_size': '🌎',
    'super_resolve': '👌👌',
    'turn_change': '⌛'
}

"Basically the same skill parser, but this time not using regex"
"Additionally a lot of these are based on t_r's work"
def process_enemy_skill(effect: str, encounter: dict, skill: dict, es: EnemySkill):
    return ""


